In [265]:
import pandas as pd

In [266]:
file_path = "../data/HSA_HD_Final.csv"  
df = pd.read_csv(file_path, sep=',')

In [267]:
df.head()

,Mã ĐTN,Giới tính,10.Điểm tổng kết HK I,10.Điểm tổng kết HK II,10.Điểm tổng kết CN,10.Học lực HK I,10.Học lực HK II,10.Học lực CN,10.Hạnh kiểm HK I,10.Hạnh kiểm HK II,...,12.GDCD HK I,12.GDCD HK II,12.GDCD CN,12.Ngoại ngữ HK I,12.Ngoại ngữ HK II,12.Ngoại ngữ CN,d1,d2,d3,diem
0,13,Nam,8.4,8.5,8.5,Giỏi,Giỏi,Giỏi,Tốt,Tốt,...,9.9,9.6,9.7,7.5,8.4,8.1,35,34,21,90
1,36,Nam,6.9,6.9,6.9,Khá,Khá,Khá,Tốt,Tốt,...,7.1,8.7,8.2,7.5,7.9,7.8,20,30,17,67
2,14,Nam,8.1,8.6,8.5,Giỏi,Giỏi,Giỏi,Tốt,Tốt,...,9.5,8.6,8.9,8.8,9.1,9.0,27,31,22,82
3,36,Nam,7.6,7.6,7.6,Khá,Khá,Khá,Tốt,Tốt,...,7.9,8.4,8.2,8.2,8.5,8.4,26,31,20,77
4,22,Nam,8.0,8.0,8.0,Khá,Khá,Khá,Tốt,Tốt,...,8.1,8.0,8.0,9.3,8.8,9.0,25,37,25,87

In [268]:
# Xóa bỏ các cột không cần thiết: Mã ĐTN, Giới tính, loại ngoại ngữ (toàn N1 hết)
col_to_drops = ['Mã ĐTN', 'Giới tính', '10.Môn ngoại ngữ', '11.Môn ngoại ngữ']
# Xóa các cột không có giá trị tính toán (điểm các kì, học lực, hạnh kiểm), chỉ lấy điểm cả năm của các môn
for col in df.columns:
    can_drop = 'tổng kết CN' in col or 'Học lực CN' in col or 'Hạnh kiểm CN' in col or 'I' in col
    if can_drop:
        col_to_drops.append(col)
df = df.drop(col_to_drops, axis=1)
# Chỉ còn lại cột các điểm cả năm và điểm d1, d2, d3 và diem HSA
df.columns

Index(['10.Toán CN', '10.Văn CN', '10.Vật lí CN', '10.Hóa học CN',
       '10.Sinh học CN', '10.Lịch sử CN', '10.Địa lí CN', '10.GDCD CN',
       '10.Ngoại ngữ CN', '11.Toán CN', '11.Văn CN', '11.Vật lí CN',
       '11.Hóa học CN', '11.Sinh học CN', '11.Lịch sử CN', '11.Địa lí CN',
       '11.GDCD CN', '11.Ngoại ngữ CN', '12.Toán CN', '12.Văn CN',
       '12.Vật lí CN', '12.Hóa học CN', '12.Sinh học CN', '12.Lịch sử CN',
       '12.Địa lí CN', '12.GDCD CN', '12.Ngoại ngữ CN', 'd1', 'd2', 'd3',
       'diem'],
      dtype='object')

In [269]:
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])  # Chỉ in ra những cột có giá trị bị thiếu

10.GDCD CN         1
10.Ngoại ngữ CN    1
11.GDCD CN         1
11.Ngoại ngữ CN    1
12.Toán CN         1
12.Văn CN          1
12.Vật lí CN       1
12.Hóa học CN      1
12.Sinh học CN     1
12.Lịch sử CN      1
12.Địa lí CN       1
12.GDCD CN         2
12.Ngoại ngữ CN    2
dtype: int64

In [270]:
# Mỗi cột thiếu 1-2 dòng dữ liệu, ta có thể xóa các dòng dữ liệu này
df.dropna(inplace=True)

In [271]:
print(df.info())  # Kiểm tra lại xem còn giá trị NaN không

<class 'pandas.core.frame.DataFrame'>
Index: 925 entries, 0 to 926
Data columns (total 31 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   10.Toán CN       925 non-null    float64
 1   10.Văn CN        925 non-null    float64
 2   10.Vật lí CN     925 non-null    float64
 3   10.Hóa học CN    925 non-null    float64
 4   10.Sinh học CN   925 non-null    float64
 5   10.Lịch sử CN    925 non-null    float64
 6   10.Địa lí CN     925 non-null    float64
 7   10.GDCD CN       925 non-null    float64
 8   10.Ngoại ngữ CN  925 non-null    float64
 9   11.Toán CN       925 non-null    float64
 10  11.Văn CN        925 non-null    float64
 11  11.Vật lí CN     925 non-null    float64
 12  11.Hóa học CN    925 non-null    float64
 13  11.Sinh học CN   925 non-null    float64
 14  11.Lịch sử CN    925 non-null    float64
 15  11.Địa lí CN     925 non-null    float64
 16  11.GDCD CN       925 non-null    float64
 17  11.Ngoại ngữ CN  925 non-null    float64
 18  12.Toán CN       925 non-null    float64
 19  12.Văn CN        925 non-null    float64
 20  12.Vật lí CN     925 non-null    float64
 21  12.Hóa học CN    925 non-null    float64
 22  12.Sinh học CN   925 non-null    float64
 23  12.Lịch sử CN    925 non-null    float64
 24  12.Địa lí CN     925 non-null    float64
 25  12.GDCD CN       925 non-null    float64
 26  12.Ngoại ngữ CN  925 non-null    float64
 27  d1               925 non-null    int64
 28  d2               925 non-null    int64
 29  d3               925 non-null    int64
 30  diem             925 non-null    int64
dtypes: float64(27), int64(4)
memory usage: 231.2 KB
None

In [272]:
# Tính điểm trung bình của từng môn trong 3 năm
mon_hoc = ["Toán", "Văn", "Vật lí", "Hóa học", "Sinh học", "Lịch sử", "Địa lí", "GDCD", "Ngoại ngữ"]
for mon in mon_hoc:
    col_names = [f"10.{mon} CN", f"11.{mon} CN", f"12.{mon} CN"]
    # Công thức tính điểm trung bình: (L10 + L11 + L12 * 2) / 4 (ưu tiên điểm lớp 12)
    df[f"{mon}_TB"] = ((df[col_names[0]] + df[col_names[1]] + df[col_names[2]] * 2) / 4).round(2)
    # df[f"{mon}_TB"] = ((df[col_names[0]] + df[col_names[1]] + df[col_names[2]]) / 3).round(2)
    df.drop(col_names, axis=1, inplace=True)  # Xóa 3 cột cũ
df["KHXH_TB"] = df[["Lịch sử_TB", "Địa lí_TB"]].mean(axis=1).round(2)
df["KHTN_TB"] = df[["Vật lí_TB", "Hóa học_TB", "Sinh học_TB"]].mean(axis=1).round(2)
df.drop(["Lịch sử_TB", "Địa lí_TB", "GDCD_TB", "Vật lí_TB", "Hóa học_TB", "Sinh học_TB"], axis=1, inplace=True)

In [273]:
df.columns

Index(['d1', 'd2', 'd3', 'diem', 'Toán_TB', 'Văn_TB', 'Ngoại ngữ_TB',
       'KHXH_TB', 'KHTN_TB'],
      dtype='object')

In [274]:
df.sort_values(by="d3", ascending=False).head(20)

     d1  d2  d3  diem  Toán_TB  Văn_TB  Ngoại ngữ_TB  KHXH_TB  KHTN_TB
395  31  35  39   105     9.38    6.00          7.52     7.24     8.47
738  30  35  39   104     8.70    7.82          8.68     8.79     8.85
635  36  35  39   110     8.95    6.68          6.50     7.72     8.46
417  30  35  38   103     9.28    8.80          8.82     9.15     9.39
439  36  35  38   109     9.35    8.32          9.38     9.18     9.54
862  35  29  38   102     9.28    7.85          9.55     9.25     9.51
555  38  33  37   108     9.68    8.23          9.85     8.52     9.33
62   36  34  37   109     9.78    7.52          8.60     8.48     9.28
578  37  37  36   110     9.52    8.22          8.33     8.54     9.42
707  38  41  36   115     8.82    7.65          8.62     8.57     9.36
346  41  36  36   113     9.73    7.88          8.43     8.56     9.17
576  35  34  36   105     9.45    7.42          7.58     8.42     9.14
460  28  33  35   100     9.02    7.40          7.78     8.14     8.76
527  30  38  35   103     9.00    7.58          8.88     9.02     9.27
723  38  33  35   106     9.05    7.22          8.65     8.52     8.92
418  38  35  35   108     9.20    7.65          7.38     7.64     8.88
677  27  35  35   105     9.05    7.55          8.50     8.60     9.13
515  45  33  35   113     9.52    8.05          8.28     8.71     9.48
279  35  37  34   106     9.68    8.35          8.98     8.68     9.51
616  31  36  34   101     9.52    7.28          8.35     8.25     9.22

In [275]:
df["KH_TB"] = df[["KHXH_TB", "KHTN_TB"]].mean(axis=1).round(2)
df.drop(["KHXH_TB", "KHTN_TB", 'Ngoại ngữ_TB'], axis=1, inplace=True)
df.to_csv("../data/HSA_HD_Final_Cleaned.csv", index=False)
print("Đã lưu file HSA_HD_Final_Cleaned.csv")
print(df.head())

Đã lưu file HSA_HD_Final_Cleaned.csv
   d1  d2  d3  diem  Toán_TB  Văn_TB  KH_TB
0  35  34  21    90     9.70    7.75   9.02
1  20  30  17    67     7.52    7.55   7.42
2  27  31  22    82     9.07    7.88   8.50
3  26  31  20    77     8.48    7.02   7.76
4  25  37  25    87     7.68    7.28   7.98